networks:
  ddbs_network:
    driver: bridge


services:
  ddbs1:
    image: mongo:4.4.4
    container_name: ddbs1
    volumes:
      - ${PWD}/ddbs/1:/data_load
    networks:
      - ddbs_network
    ports:
      - "27001:27017"

  ddbs2:
    image: mongo:4.4.4
    container_name: ddbs2
    volumes:
      - ${PWD}/ddbs/2:/data_load
    networks:
      - ddbs_network
    ports:
      - "27002:27017"

  ddbs1_bak:
    image: mongo:4.4.4
    container_name: ddbs1_bak
    volumes:
      - ${PWD}/ddbs/1:/data_load
    networks:
      - ddbs_network
    ports:
      - "27003:27017"

  ddbs2_bak:
    image: mongo:4.4.4
    container_name: ddbs2_bak
    volumes:
      - ${PWD}/ddbs/2:/data_load
    networks:
      - ddbs_network
    ports:
      - "27004:27017"

  tracker:
    image: delron/fastdfs
    container_name: tracker
    networks:
      - ddbs_network
    ports:
      - "22122:22122"
    command: "tracker"

  storage1:
    image: delron/fastdfs
    container_name: storage1
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes:
      - ${PWD}/db-generation/articles:/etc/fdfs_buffer/
      # - ${PWD}/configs/storage1.conf:/etc/fdfs/storage.conf
      - ${PWD}/configs/storage_nginx.conf:/usr/local/nginx/conf/nginx.conf
    depends_on:
      - tracker
    networks:
      - ddbs_network
    ports:
      - "8888:8888"
      - "23000:23000"
    command: "storage"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ${PWD}/configs/nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - ddbs_network